/****************************************************************************/
/***                                                                      ***/
/***   header file generated by ASC 1.63 - altona shader compiler.        ***/
/***                                                                      ***/
/****************************************************************************/

#ifndef HEADER_WZ4FRLIB_EASTER_SHADER_ASC
#define HEADER_WZ4FRLIB_EASTER_SHADER_ASC

#include "base/graphics.hpp"

/****************************************************************************/

enum Julia4DPSPerm
{
  Julia4DPSPermMask_ZOnly                   = 0x0001,
};

/****************************************************************************/

struct Julia4DVSPara
{
public:
  sMatrix44 mvp;
  sMatrix44 Camera;
  sVector4 UVOffset;
  static const sInt RegStart = 0;
  static const sInt RegCount = 9;
  static const sInt Slot = sCBUFFER_VS|0;
#line 22 "easter_shader.asc"
  void Set(const sViewport &view, const sMatrix34 &cam);
#line 33 "easter_shader.hpp"
};

struct Julia4DPSPara
{
public:
  sVector4 C;
  sVector4 Params1;
  sVector4 ClipPlane;
  sMatrix34CM mv;
  sVector4 Color;
  sVector4 ldir_vs;
  sVector4 lc_front;
  sVector4 lc_mid;
  sVector4 lc_back;
  sVector4 lc_spec;
  sVector4 ambient;
  sVector4 Fog;
  sVector4 FogColor;
  static const sInt RegStart = 0;
  static const sInt RegCount = 15;
  static const sInt Slot = sCBUFFER_PS|0;
#line 55 "easter_shader.hpp"
};


/****************************************************************************/

class Julia4DPass1Mtrl : public sMaterial
{
  static sShader *VS();
  static sShader *PS();
public:
  void SelectShaders(sVertexFormatHandle *);
};
class Julia4DPass2Material : public sMaterial
{
  static sShader *VS();
  static sShader *PS();
public:
  void SelectShaders(sVertexFormatHandle *);
};
class Julia4DPass3Material : public sMaterial
{
  static sShader *VS();
  static sShader *PS();
public:
  void SelectShaders(sVertexFormatHandle *);
};

/****************************************************************************/

#endif

