/****************************************************************************/
/***                                                                      ***/
/***   header file generated by ASC 1.63 - altona shader compiler.        ***/
/***                                                                      ***/
/****************************************************************************/

#ifndef HEADER_WZ4FRLIB_FR063_TRON_SHADER_ASC
#define HEADER_WZ4FRLIB_FR063_TRON_SHADER_ASC

#include "base/graphics.hpp"

/****************************************************************************/

enum StaticParticleExtPSPerm
{
  StaticParticleExtPSPermMask_Tex1          = 0x0001,
};

/****************************************************************************/

struct FR063StaticParticleVSPara
{
public:
  sMatrix44 mvp;
  sVector4 di;
  sVector4 dj;
  static const sInt RegStart = 0;
  static const sInt RegCount = 6;
  static const sInt Slot = sCBUFFER_VS|0;
#line 31 "fr063_tron_shader.hpp"
};

struct FR063StaticParticlePSPara
{
public:
  sVector4 fade0col;
  static const sInt RegStart = 0;
  static const sInt RegCount = 1;
  static const sInt Slot = sCBUFFER_PS|0;
#line 41 "fr063_tron_shader.hpp"
};

struct FR063BallVSPara
{
public:
  sMatrix44 mvp;
  sMatrix44 mv;
  sVector4 di;
  sVector4 dj;
  static const sInt RegStart = 0;
  static const sInt RegCount = 10;
  static const sInt Slot = sCBUFFER_VS|0;
#line 54 "fr063_tron_shader.hpp"
};

struct FR063BallPSPara
{
public:
  sMatrix44 proj;
  sVector4 lightpos;
  sVector4 campos;
  sVector4 ambcol;
  sVector4 diffcol;
  sVector4 speccol;
  sVector4 specprm;
  static const sInt RegStart = 0;
  static const sInt RegCount = 10;
  static const sInt Slot = sCBUFFER_PS|0;
#line 70 "fr063_tron_shader.hpp"
};

struct StaticParticleExtVSPara
{
public:
  sMatrix44 mvp;
  static const sInt RegStart = 0;
  static const sInt RegCount = 4;
  static const sInt Slot = sCBUFFER_VS|0;
#line 80 "fr063_tron_shader.hpp"
};

struct StaticParticleExtPSPara
{
public:
  sVector4 col;
  sVector4 fade0col;
  static const sInt RegStart = 0;
  static const sInt RegCount = 2;
  static const sInt Slot = sCBUFFER_PS|0;
#line 91 "fr063_tron_shader.hpp"
};


/****************************************************************************/

class FR063StaticParticleShader : public sMaterial
{
  static sShader *VS();
  static sShader *PS();
public:
  void SelectShaders(sVertexFormatHandle *);
};
class FR063BallShader : public sMaterial
{
  static sShader *VS();
  static sShader *PS();
public:
  void SelectShaders(sVertexFormatHandle *);
};
class StaticParticleShaderExt : public sMaterial
{
  static sShader *VS();
  static sShader *PS(sInt);
public:
  void SelectShaders(sVertexFormatHandle *);
};

/****************************************************************************/

#endif

