/****************************************************************************/
/***                                                                      ***/
/***   header file generated by ASC 1.63 - altona shader compiler.        ***/
/***                                                                      ***/
/****************************************************************************/

#ifndef HEADER_WZ4FRLIB_FR063_MANDELBULB_SHADER_ASC
#define HEADER_WZ4FRLIB_FR063_MANDELBULB_SHADER_ASC

#include "base/graphics.hpp"

/****************************************************************************/


/****************************************************************************/

struct MandelMathVP
{
public:
  sMatrix44 mvp;
  static const sInt RegStart = 0;
  static const sInt RegCount = 4;
  static const sInt Slot = sCBUFFER_VS|0;
#line 25 "fr063_mandelbulb_shader.hpp"
};

struct MandelMathPP
{
public:
  sVector4 para;
  static const sInt RegStart = 0;
  static const sInt RegCount = 1;
  static const sInt Slot = sCBUFFER_PS|0;
#line 35 "fr063_mandelbulb_shader.hpp"
};


/****************************************************************************/

class MandelMath : public sMaterial
{
  static sShader *VS();
  static sShader *PS();
public:
  void SelectShaders(sVertexFormatHandle *);
};

/****************************************************************************/

#endif

