/****************************************************************************/
/***                                                                      ***/
/***   header file generated by ASC 1.63 - altona shader compiler.        ***/
/***                                                                      ***/
/****************************************************************************/

#ifndef HEADER_WZ4FRLIB_FXPARTICLE_SHADER_ASC
#define HEADER_WZ4FRLIB_FXPARTICLE_SHADER_ASC

#include "base/graphics.hpp"

/****************************************************************************/

enum StaticParticlePSPerm
{
  StaticParticlePSPermMask_TEX1             = 0x0001,
  StaticParticlePSPermMask_ALPHATEST        = 0x0002,
};
enum MetaballsPartPSPerm
{
  MetaballsPartPSPermMask_Tex               = 0x0001,
};

/****************************************************************************/

struct StaticParticleVSPara
{
public:
  sMatrix44 mvp;
  sVector4 di;
  sVector4 dj;
  sVector4 trans;
  static const sInt RegStart = 0;
  static const sInt RegCount = 7;
  static const sInt Slot = sCBUFFER_VS|0;
#line 37 "fxparticle_shader.hpp"
};

struct StaticParticlePSPara
{
public:
  sVector4 col;
  sVector4 fade0col;
  static const sInt RegStart = 0;
  static const sInt RegCount = 2;
  static const sInt Slot = sCBUFFER_PS|0;
#line 48 "fxparticle_shader.hpp"
};

struct MetaballsPartVSPara
{
public:
  sMatrix44 mvp;
  sVector4 uvoffset;
  sVector4 ray00;
  sVector4 ray01;
  sVector4 ray10;
  sVector4 ray11;
  sVector4 CamPos;
  static const sInt RegStart = 0;
  static const sInt RegCount = 10;
  static const sInt Slot = sCBUFFER_VS|0;
#line 64 "fxparticle_shader.hpp"
};

struct MetaballsTraceVSPara
{
public:
  sMatrix44 mvp;
  sVector4 ray00;
  sVector4 ray01;
  sVector4 ray10;
  sVector4 ray11;
  sVector4 CamPos;
  static const sInt RegStart = 0;
  static const sInt RegCount = 9;
  static const sInt Slot = sCBUFFER_VS|0;
#line 79 "fxparticle_shader.hpp"
};


/****************************************************************************/

class StaticParticleShader : public sMaterial
{
  static sShader *VS();
  static sShader *PS(sInt);
public:
  StaticParticleShader();
  void SelectShaders(sVertexFormatHandle *);
#line 38 "fxparticle_shader.asc"

    enum ExtraBits
    {
      EXTRA_TEX1      = 0x01,
      EXTRA_ALPHATEST = 0x02,
    };
    sInt Extra;
  
#line 101 "fxparticle_shader.cpp"
};
class MetaballsPartMtrl : public sMaterial
{
  static sShader *VS();
  static sShader *PS(sInt);
public:
  void SelectShaders(sVertexFormatHandle *);
};
class MetaballsTraceMtrl : public sMaterial
{
  static sShader *VS();
  static sShader *PS();
public:
  void SelectShaders(sVertexFormatHandle *);
};

/****************************************************************************/

#endif

