/****************************************************************************/
/***                                                                      ***/
/***   header file generated by ASC 1.63 - altona shader compiler.        ***/
/***                                                                      ***/
/****************************************************************************/

#ifndef HEADER_WZ4FRLIB_WZ4_ROVEMTRL_SHADER_ASC
#define HEADER_WZ4FRLIB_WZ4_ROVEMTRL_SHADER_ASC

#include "base/graphics.hpp"

/****************************************************************************/

enum RoveShaderVPerm
{
  RoveShaderVPerm_TexOff                    = 0x0000,
  RoveShaderVPerm_Tex1                      = 0x0001,
  RoveShaderVPerm_Tex2                      = 0x0002,
  RoveShaderVPermMask_Tex                   = 0x0003,
  RoveShaderVPerm_DetailUV                  = 0x0000,
  RoveShaderVPerm_DetailPos                 = 0x0004,
  RoveShaderVPerm_DetailNorm                = 0x0008,
  RoveShaderVPerm_DetailRefl                = 0x000c,
  RoveShaderVPermMask_Detail                = 0x001c,
  RoveShaderVPerm_MatrixOff                 = 0x0000,
  RoveShaderVPerm_MatrixSkin                = 0x0020,
  RoveShaderVPerm_MatrixInst                = 0x0040,
  RoveShaderVPermMask_Matrix                = 0x0060,
};
enum RoveShaderPPerm
{
  RoveShaderPPermMask_Tex1                  = 0x0001,
  RoveShaderPPerm_Tex2Off                   = 0x0000,
  RoveShaderPPerm_Tex2Add                   = 0x0002,
  RoveShaderPPerm_Tex2Mul                   = 0x0004,
  RoveShaderPPermMask_Tex2                  = 0x0006,
  RoveShaderPPerm_FogOff                    = 0x0000,
  RoveShaderPPerm_FogOn                     = 0x0008,
  RoveShaderPPerm_FogBlack                  = 0x0010,
  RoveShaderPPerm_FogClip3                  = 0x0018,
  RoveShaderPPermMask_Fog                   = 0x0038,
  RoveShaderPPermMask_Clip                  = 0x0040,
};

/****************************************************************************/

struct RoveShaderVEnv
{
public:
  sMatrix44 mvp;
  sMatrix44 mv;
  sVector4 EyePos;
  static const sInt RegStart = 0;
  static const sInt RegCount = 9;
  static const sInt Slot = sCBUFFER_VS|0;
#line 57 "wz4_rovemtrl_shader.hpp"
};

struct RoveMtrlModelPara
{
public:
  sVector4 m[3];
  static const sInt RegStart = 28;
  static const sInt RegCount = 3;
  static const sInt Slot = sCBUFFER_VS|1;
#line 67 "wz4_rovemtrl_shader.hpp"
};

struct RoveShaderVPara
{
public:
  sVector4 texmat[4];
  static const sInt RegStart = 24;
  static const sInt RegCount = 4;
  static const sInt Slot = sCBUFFER_VS|2;
#line 77 "wz4_rovemtrl_shader.hpp"
};

struct RoveShaderPEnv
{
public:
  sVector4 FogPara;
  sVector4 FogColor;
  sVector4 ClipPlane[4];
  sVector4 Ambient;
  sVector4 LightPos[3];
  sVector4 LightCol[3];
  sVector4 LightInvSqRange;
  static const sInt RegStart = 0;
  static const sInt RegCount = 14;
  static const sInt Slot = sCBUFFER_PS|0;
#line 93 "wz4_rovemtrl_shader.hpp"
};


/****************************************************************************/

class RoveShader : public sMaterial
{
  static sShader *VS(sInt);
  static sShader *PS(sInt);
public:
  RoveShader();
  void SelectShaders(sVertexFormatHandle *);
#line 231 "wz4_rovemtrl_shader.asc"

    enum ExtraBits
    {
      Extra_Fog           = 0x0001,
      Extra_FogBlack      = 0x0002,
      Extra_TexMul        = 0x0004,
      Extra_Clip          = 0x0008,

      ExtraDetailMask     = 0x00f0,
      ExtraDetailUV       = 0x0000,
      ExtraDetailPos      = 0x0010,
      ExtraDetailNorm     = 0x0020,
      ExtraDetailRefl     = 0x0030,
    };
    sInt Extra;
  
#line 123 "wz4_rovemtrl_shader.cpp"
};

/****************************************************************************/

#endif

