#pragma once

#define qglEnable glEnable
#define qglBlendFunc glBlendFunc
#define qglDisable glDisable
#define qglUseProgram glUseProgram
#define qglViewport glViewport
#define qglUniform1i glUniform1i 
#define qglUniformMatrix4fv glUniformMatrix4fv
#define qglBindVertexArray glBindVertexArray
#define qglBindBuffer glBindBuffer
#define qglBufferData glBufferData
#define qglBindTexture glBindTexture
#define qglScissor glScissor
#define qglDrawElements glDrawElements
#define qglGetIntegerv glGetIntegerv
#define qglGenTextures glGenTextures
#define qglTexParameteri glTexParameteri
#define qglTexImage2D glTexImage2D
#define qglCreateProgram glCreateProgram
#define qglCreateShader glCreateShader
#define qglShaderSource glShaderSource
#define qglCompileShader glCompileShader
#define qglAttachShader glAttachShader
#define qglLinkProgram glLinkProgram
#define qglGetUniformLocation glGetUniformLocation
#define qglGetAttribLocation glGetAttribLocation
#define qglGenBuffers glGenBuffers
#define qglGenVertexArrays glGenVertexArrays
#define qglEnableVertexAttribArray glEnableVertexAttribArray
#define qglVertexAttribPointer glVertexAttribPointer
#define qglDeleteVertexArrays glDeleteVertexArrays
#define qglDeleteBuffers glDeleteBuffers
#define qglDetachShader glDetachShader
#define qglDeleteShader glDeleteShader
#define qglDeleteProgram glDeleteProgram
#define qglDeleteTextures glDeleteTextures
#define qglClear glClear